language: php

php:
  - 5.6

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - mkdir -p ./build/coverage

script:
  - ./vendor/bin/phpunit --verbose

after_success:
  - ./vendor/bin/coveralls -v
